---
- name: Deploy SSH hardening config
  template:
    src: hardening.conf.j2
    dest: /etc/ssh/sshd_config.d/hardening.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart sshd

- name: Ensure sshd is enabled
  service:
    name: sshd
    enabled: true

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
