---
- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Set default incoming policy to deny
  ufw:
    direction: incoming
    default: deny

- name: Set default outgoing policy to allow
  ufw:
    direction: outgoing
    default: allow

- name: Allow SSH
  ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp
    comment: SSH

- name: Allow HTTP
  ufw:
    rule: allow
    port: "80"
    proto: tcp
    comment: HTTP

- name: Allow HTTPS
  ufw:
    rule: allow
    port: "443"
    proto: tcp
    comment: HTTPS

- name: Enable UFW
  ufw:
    state: enabled
