---
- name: Install unattended-upgrades
  apt:
    name:
      - unattended-upgrades
      - apt-listchanges
    state: present

- name: Configure auto-upgrades
  copy:
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
      APT::Periodic::AutocleanInterval "7";
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: "0644"

- name: Enable unattended-upgrades
  command: dpkg-reconfigure -plow unattended-upgrades
  environment:
    DEBIAN_FRONTEND: noninteractive
  changed_when: false
